/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package turistInfo.korisnik;

import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author raka
 */
public class GlavnaKorisnickaFormaGUI extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaKorisnickaFormaGUI
     */
    private  int ukupnoTuristickihAtrakcija;
    private static int brojac = 1;
    private int brojacKorisnika;
   // private PomocnaKlasa pk = new PomocnaKlasa();
    
    public GlavnaKorisnickaFormaGUI() {
        initComponents();
        this.setTitle("Korisnička aplikacija");
        this.brojacKorisnika = brojac;
        brojac++;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
        setLocationRelativeTo(null);
        ArrayList<JSpinner> spineri = new ArrayList<>();
        spineri.add(spinerBrojTurista);
        spineri.add(spinerBrojTuristickihObjekata);
        spineri.add(spinerMatricaM);
        spineri.add(spinerMatricaN);
        PomocnaKlasa.podesiSpinere(spineri);
        
        
    }

    public  int getUkupnoTuristickihAtrakcija() {
        return ukupnoTuristickihAtrakcija;
    }

    public  int getBrojacKorisnika() {
        return brojacKorisnika;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dugmePokrenSimulaciju = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spinerMatricaN = new javax.swing.JSpinner();
        spinerMatricaM = new javax.swing.JSpinner();
        spinerBrojTurista = new javax.swing.JSpinner();
        spinerBrojTuristickihObjekata = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Broj turista: ");

        jLabel2.setText("Dimenzije matrice: ");

        jLabel3.setText("Broj turističkih objekata:");

        dugmePokrenSimulaciju.setText("Pokreni simulaciju");
        dugmePokrenSimulaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dugmePokrenSimulacijuActionPerformed(evt);
            }
        });

        jLabel4.setText("X");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setText("S I M U L A C I J A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinerBrojTuristickihObjekata, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinerBrojTurista, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spinerMatricaN, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinerMatricaM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dugmePokrenSimulaciju)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinerBrojTurista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(spinerMatricaN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinerMatricaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spinerBrojTuristickihObjekata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(dugmePokrenSimulaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dugmePokrenSimulacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dugmePokrenSimulacijuActionPerformed
       int m = (int) spinerMatricaM.getValue();
       int n = (int) spinerMatricaN.getValue();
       int brojTurista = (int) spinerBrojTurista.getValue();
       int brojTuristickihAtrakcija = (int) spinerBrojTuristickihObjekata.getValue();
       ukupnoTuristickihAtrakcija = brojTuristickihAtrakcija;
       
       //pk.postaviTuristickeAtrakcijeNaMapu(m, n, brojTuristickihAtrakcija);
       //PomocnaKlasa.postaviTuristeNaMapu(brojTurista);
      // new SimulacijaFormaGUI(m, n, brojTurista);
     //  this.setVisible(false);
     GlavnaKorisnickaFormaGUI gfk = this;
       Runnable runnable = new Runnable() {
            @Override
            public void run() {
                new SimulacijaFormaGUI(m, n, brojTurista, ukupnoTuristickihAtrakcija, gfk).setVisible(true);
            }
        };
        new Thread(runnable).start();
       // new GlavnaKorisnickaFormaGUI();
       this.dispose();
    }//GEN-LAST:event_dugmePokrenSimulacijuActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dugmePokrenSimulaciju;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner spinerBrojTurista;
    private javax.swing.JSpinner spinerBrojTuristickihObjekata;
    private javax.swing.JSpinner spinerMatricaM;
    private javax.swing.JSpinner spinerMatricaN;
    // End of variables declaration//GEN-END:variables
}
