/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package turistInfo.korisnik;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import jdk.jfr.events.FileReadEvent;
import static jdk.nashorn.internal.objects.NativeMath.round;
import turistInfo.admin.Crkva;
import turistInfo.admin.IstorijskiSpomenik;
import turistInfo.admin.Muzej;
import turistInfo.admin.TuristickaAtrakcija;
import turistInfo.admin.ZabavniPark;
import turistInfo.poruka.Poruka;

/**
 *
 * @author raka
 */
public class Top5FormaGUI extends javax.swing.JFrame {

    /**
     * Creates new form Top5FormaGUI
     */
    private ArrayList<Turista> top5;
    private int ukupnoTuristickihAtrakcija;
    private DefaultTableModel modelTabelaTop5;
    private GlavnaKorisnickaFormaGUI gkf;
    private KomunikacijaSaServerom kss;
    private int brojacKorisnika;

    public Top5FormaGUI(ArrayList<Turista> top5, GlavnaKorisnickaFormaGUI gkf, KomunikacijaSaServerom kss) {
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.top5 = top5;
        this.gkf = gkf;
        this.kss = kss;
        this.setTitle("Top 5");
        this.brojacKorisnika = kss.getBrojacKorisnika();
        this.modelTabelaTop5 = (DefaultTableModel) tabelaTop5.getModel();
        this.ukupnoTuristickihAtrakcija = gkf.getUkupnoTuristickihAtrakcija();
        popuniTabeluTop5(top5, tabelaTop5);
    }

    public void popuniTabeluTop5(ArrayList<Turista> top5, JTable tabelaTop5) {

        //sviDogadjaji = dogadjaji;
        DefaultTableCellRenderer centriranje = new DefaultTableCellRenderer();
        centriranje.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        DefaultTableCellRenderer centriranjeLijevo = new DefaultTableCellRenderer();
        centriranjeLijevo.setHorizontalAlignment(DefaultTableCellRenderer.LEFT);
        DefaultTableCellRenderer centriranjeDesno = new DefaultTableCellRenderer();
        centriranjeDesno.setHorizontalAlignment(DefaultTableCellRenderer.RIGHT);
        tabelaTop5.getColumnModel().getColumn(0).setCellRenderer(centriranje);
        tabelaTop5.getColumnModel().getColumn(1).setCellRenderer(centriranjeLijevo); 
        tabelaTop5.getColumnModel().getColumn(2).setCellRenderer(centriranjeDesno);
        tabelaTop5.getColumnModel().getColumn(3).setCellRenderer(centriranjeDesno);
        //brisanje tabele
        int rowCount = modelTabelaTop5.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            modelTabelaTop5.removeRow(i);
        }

        int redniBroj = 1;
        for (Turista turista : top5) {
           // System.out.println("==========================Turista iz top 5: " + turista.getIme());
            String imeTuriste = turista.getIme();
            int brojPosjecenihAtrakcija = turista.getBrojPosjecenihMjesta();
            double postotakPosjecenosti = (((double) turista.getBrojPosjecenihMjesta() / (double) ukupnoTuristickihAtrakcija) * 100.0);
            DecimalFormat df = new DecimalFormat("0.00");

            //System.out.println("==========================POSTOTAK: " + df.format(postotakPosjecenosti));
            modelTabelaTop5.addRow(new Object[]{redniBroj, imeTuriste, brojPosjecenihAtrakcija, df.format(postotakPosjecenosti)});

            redniBroj++;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTop5 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        dugmeLetak = new javax.swing.JButton();
        dugmePreuzmiRezultate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelaTop5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "R.B.", "Turista", "Posjecenih TA", "Posjecenih TA (%)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaTop5);
        if (tabelaTop5.getColumnModel().getColumnCount() > 0) {
            tabelaTop5.getColumnModel().getColumn(0).setMinWidth(45);
            tabelaTop5.getColumnModel().getColumn(0).setPreferredWidth(45);
            tabelaTop5.getColumnModel().getColumn(0).setMaxWidth(50);
            tabelaTop5.getColumnModel().getColumn(1).setMinWidth(120);
            tabelaTop5.getColumnModel().getColumn(1).setPreferredWidth(130);
            tabelaTop5.getColumnModel().getColumn(1).setMaxWidth(140);
            tabelaTop5.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("TOP 5");

        dugmeLetak.setText("Letak");
        dugmeLetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dugmeLetakActionPerformed(evt);
            }
        });

        dugmePreuzmiRezultate.setText("Preuzmi rezultate");
        dugmePreuzmiRezultate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dugmePreuzmiRezultateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dugmeLetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dugmePreuzmiRezultate, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dugmeLetak, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dugmePreuzmiRezultate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dugmeLetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dugmeLetakActionPerformed
        int selektovaniTurista = tabelaTop5.getSelectedRow();
        if(selektovaniTurista > -1){
        String letak = "";
        Turista odabraniTurista = top5.get(selektovaniTurista);
        File fajlLetka;
        BufferedReader citaj;
        try {

            File folder = odabraniTurista.getFajl();//folder turiste
            File[] listOfFiles = folder.listFiles();
            boolean postojiLetak = false;
            
            for (File file : listOfFiles) {
                if (file.isFile()) {
                    if (file.getName().endsWith(".txt")) {
                        postojiLetak = true;
                        fajlLetka = file;
                        citaj = new BufferedReader(new FileReader(fajlLetka));
                        StringBuilder sb = new StringBuilder();
                        String line = citaj.readLine();
                        while (line != null) {
                            sb.append(line);
                            sb.append(System.lineSeparator());
                            line = citaj.readLine();
                        }
                        letak = sb.toString();
                        JTextArea textArea = new JTextArea(11, 45);
                        textArea.setLineWrap(true);
                        textArea.setText(letak);
                        textArea.setEditable(false);
                        // wrap a scrollpane around it
                        JScrollPane scrollPane = new JScrollPane(textArea);
                        // display them in a message dialog
                        JOptionPane.showMessageDialog(null, scrollPane, "Letak", JOptionPane.INFORMATION_MESSAGE);
                        break;
                    }
                }
            }
            
            
           if(postojiLetak == false){
            JOptionPane.showMessageDialog(null, "Turista nema sakupljenih letaka!");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "Nije selektovan ni jedan turista! ");
        }
    }//GEN-LAST:event_dugmeLetakActionPerformed

    private void dugmePreuzmiRezultateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dugmePreuzmiRezultateActionPerformed
        try{
        kss.oos.writeObject(new Poruka("rezultati"));
        File rezultatiFajl = new File(".\\src\\turistInfo\\admin\\fajlovi\\" + brojacKorisnika);
        if(!rezultatiFajl.exists()){
            rezultatiFajl.mkdir();
        }
        
        kss.primiFajl(new File(rezultatiFajl.getPath() + "\\rezultati.csv"));
        JOptionPane.showMessageDialog(null, "Fajl: rezultati.csv je uspjesno primljen sa servera!");
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_dugmePreuzmiRezultateActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dugmeLetak;
    private javax.swing.JButton dugmePreuzmiRezultate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTop5;
    // End of variables declaration//GEN-END:variables
}
